# Form implementation generated from reading ui file 'a_table.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChooseItemUi(object):
    def setupUi(self, ChooseItemUi):
        ChooseItemUi.setObjectName("ChooseItemUi")
        ChooseItemUi.resize(1000, 600)
        ChooseItemUi.setMinimumSize(QtCore.QSize(1000, 600))
        ChooseItemUi.setMaximumSize(QtCore.QSize(1000, 600))
        ChooseItemUi.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        ChooseItemUi.setStyleSheet("background-color:#033a63;")
        self.gridLayout = QtWidgets.QGridLayout(ChooseItemUi)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.table = QtWidgets.QTableWidget(parent=ChooseItemUi)
        self.table.setStyleSheet("background-color:white")
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(2, item)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.table)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.switch_time = QtWidgets.QPushButton(parent=ChooseItemUi)
        self.switch_time.setMinimumSize(QtCore.QSize(0, 60))
        self.switch_time.setMaximumSize(QtCore.QSize(16777215, 60))
        self.switch_time.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.switch_time.setStyleSheet("QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.switch_time.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/add_item.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.switch_time.setIcon(icon)
        self.switch_time.setIconSize(QtCore.QSize(50, 50))
        self.switch_time.setFlat(True)
        self.switch_time.setObjectName("switch_time")
        self.horizontalLayout_2.addWidget(self.switch_time)
        self.cancel_btn = QtWidgets.QPushButton(parent=ChooseItemUi)
        self.cancel_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.cancel_btn.setMaximumSize(QtCore.QSize(16777215, 60))
        self.cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.cancel_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/cancel.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cancel_btn.setIcon(icon1)
        self.cancel_btn.setIconSize(QtCore.QSize(50, 50))
        self.cancel_btn.setFlat(True)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.title = QtWidgets.QLabel(parent=ChooseItemUi)
        self.title.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setStyleSheet("color:white")
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_5.addWidget(self.title)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(ChooseItemUi)
        self.cancel_btn.clicked.connect(ChooseItemUi.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ChooseItemUi)

    def retranslateUi(self, ChooseItemUi):
        _translate = QtCore.QCoreApplication.translate
        ChooseItemUi.setWindowTitle(_translate("ChooseItemUi", "Form"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("ChooseItemUi", "الإسم"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("ChooseItemUi", "المرجع"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("ChooseItemUi", "البيع بـ"))
        self.switch_time.setShortcut(_translate("ChooseItemUi", "Return"))
        self.cancel_btn.setShortcut(_translate("ChooseItemUi", "Esc"))
        self.title.setText(_translate("ChooseItemUi", "العنوان يظهر هنا"))
