# Form implementation generated from reading ui file 'analysis_tables.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(828, 439)
        Form.setStyleSheet("background-color:#033a63;")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 811, 341))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.expenses_table = QtWidgets.QTableWidget(parent=self.horizontalLayoutWidget)
        self.expenses_table.setStyleSheet("background-color:white;\n"
"")
        self.expenses_table.setObjectName("expenses_table")
        self.expenses_table.setColumnCount(2)
        self.expenses_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        item.setFont(font)
        self.expenses_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        item.setFont(font)
        self.expenses_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.expenses_table)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 60))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.incomes_table = QtWidgets.QTableWidget(parent=self.horizontalLayoutWidget)
        self.incomes_table.setStyleSheet("background-color:white;\n"
"")
        self.incomes_table.setObjectName("incomes_table")
        self.incomes_table.setColumnCount(2)
        self.incomes_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        item.setFont(font)
        self.incomes_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        item.setFont(font)
        self.incomes_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.incomes_table)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 479, 16, 16))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cancel_btn = QtWidgets.QPushButton(parent=Form)
        self.cancel_btn.setGeometry(QtCore.QRect(380, 370, 60, 58))
        self.cancel_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_btn.setStyleSheet("QPushButton{\n"
"    border: 1px solid gray;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.cancel_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/cancel.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cancel_btn.setIcon(icon)
        self.cancel_btn.setIconSize(QtCore.QSize(50, 50))
        self.cancel_btn.setFlat(True)
        self.cancel_btn.setObjectName("cancel_btn")

        self.retranslateUi(Form)
        self.cancel_btn.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "المخروجات"))
        item = self.expenses_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "الخرج"))
        item = self.expenses_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "المبلغ"))
        self.label_2.setText(_translate("Form", "المداخيل"))
        item = self.incomes_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "الدخل"))
        item = self.incomes_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "المبلغ"))
