# Form implementation generated from reading ui file 'confirmation_msg.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 200)
        Dialog.setMinimumSize(QtCore.QSize(450, 200))
        Dialog.setMaximumSize(QtCore.QSize(450, 260))
        Dialog.setStyleSheet("background-color:#033a63;")
        self.msg = QtWidgets.QLabel(parent=Dialog)
        self.msg.setGeometry(QtCore.QRect(10, 30, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.msg.setFont(font)
        self.msg.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.msg.setStyleSheet("color:white;")
        self.msg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.msg.setObjectName("msg")
        self.cancel_btn = QtWidgets.QPushButton(parent=Dialog)
        self.cancel_btn.setGeometry(QtCore.QRect(80, 110, 60, 60))
        self.cancel_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.cancel_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.cancel_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icons/cancel.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cancel_btn.setIcon(icon)
        self.cancel_btn.setIconSize(QtCore.QSize(50, 50))
        self.cancel_btn.setFlat(True)
        self.cancel_btn.setObjectName("cancel_btn")
        self.apply_btn = QtWidgets.QPushButton(parent=Dialog)
        self.apply_btn.setGeometry(QtCore.QRect(300, 110, 60, 60))
        self.apply_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.apply_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.apply_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.apply_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../icons/apply.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.apply_btn.setIcon(icon1)
        self.apply_btn.setIconSize(QtCore.QSize(50, 50))
        self.apply_btn.setFlat(True)
        self.apply_btn.setObjectName("apply_btn")

        self.retranslateUi(Dialog)
        self.cancel_btn.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.msg.setText(_translate("Dialog", "نافذة التأكيد"))
