# Form implementation generated from reading ui file 'database.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 402)
        Form.setStyleSheet("background-color:#033a63;")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(160, 30, 211, 60))
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.cancel_btn = QtWidgets.QPushButton(parent=Form)
        self.cancel_btn.setGeometry(QtCore.QRect(130, 330, 60, 60))
        self.cancel_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.cancel_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.cancel_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/cancel.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cancel_btn.setIcon(icon)
        self.cancel_btn.setIconSize(QtCore.QSize(50, 50))
        self.cancel_btn.setFlat(True)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 110, 481, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 60))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.browse_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.browse_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.browse_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.browse_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.browse_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.browse_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/browse.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.browse_btn.setIcon(icon1)
        self.browse_btn.setIconSize(QtCore.QSize(50, 50))
        self.browse_btn.setFlat(True)
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout.addWidget(self.browse_btn)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(190, 210, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setObjectName("label_3")
        self.current_path = QtWidgets.QLabel(parent=Form)
        self.current_path.setGeometry(QtCore.QRect(10, 260, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.current_path.setFont(font)
        self.current_path.setStyleSheet("color:yellow")
        self.current_path.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.current_path.setObjectName("current_path")
        self.save_btn = QtWidgets.QPushButton(parent=Form)
        self.save_btn.setGeometry(QtCore.QRect(320, 330, 60, 60))
        self.save_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.save_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.save_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.save_btn.setIcon(icon2)
        self.save_btn.setIconSize(QtCore.QSize(50, 50))
        self.save_btn.setFlat(True)
        self.save_btn.setObjectName("save_btn")

        self.retranslateUi(Form)
        self.cancel_btn.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "مكان حفظ البيانات"))
        self.label_2.setText(_translate("Form", "حدد مكان قاعدة البيانات : "))
        self.label_3.setText(_translate("Form", "مسار قاعدة البيانات على الجهاز حاليا : "))
        self.current_path.setText(_translate("Form", "المسار الإفتراض حليا هو : documents"))
