# Form implementation generated from reading ui file 'editable_items.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChooseItemUi(object):
    def setupUi(self, ChooseItemUi):
        ChooseItemUi.setObjectName("ChooseItemUi")
        ChooseItemUi.resize(1000, 600)
        ChooseItemUi.setMinimumSize(QtCore.QSize(1000, 600))
        ChooseItemUi.setMaximumSize(QtCore.QSize(1000, 600))
        ChooseItemUi.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        ChooseItemUi.setStyleSheet("background-color:#033a63;")
        self.gridLayout = QtWidgets.QGridLayout(ChooseItemUi)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.table = QtWidgets.QTableWidget(parent=ChooseItemUi)
        self.table.setStyleSheet("background-color:white")
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(2, item)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.table)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_btn = QtWidgets.QPushButton(parent=ChooseItemUi)
        self.edit_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.edit_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.edit_btn.setText("")
        self.edit_btn.setIconSize(QtCore.QSize(50, 50))
        self.edit_btn.setFlat(True)
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout_2.addWidget(self.edit_btn)
        self.delete_btn = QtWidgets.QPushButton(parent=ChooseItemUi)
        self.delete_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.delete_btn.setMaximumSize(QtCore.QSize(16777215, 60))
        self.delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.delete_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.delete_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/add_item.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_btn.setIcon(icon)
        self.delete_btn.setIconSize(QtCore.QSize(50, 50))
        self.delete_btn.setFlat(True)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_2.addWidget(self.delete_btn)
        self.cancel_btn = QtWidgets.QPushButton(parent=ChooseItemUi)
        self.cancel_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.cancel_btn.setMaximumSize(QtCore.QSize(16777215, 60))
        self.cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_btn.setStyleSheet("QPushButton:hover{\n"
"    background-color:#3f5482;\n"
"    border: 1px solid #3f5482;\n"
"}")
        self.cancel_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/cancel.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cancel_btn.setIcon(icon1)
        self.cancel_btn.setIconSize(QtCore.QSize(50, 50))
        self.cancel_btn.setFlat(True)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.search_box = QtWidgets.QLineEdit(parent=ChooseItemUi)
        self.search_box.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.search_box.setFont(font)
        self.search_box.setStyleSheet("background-color:white;")
        self.search_box.setMaxLength(24)
        self.search_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.search_box.setDragEnabled(False)
        self.search_box.setObjectName("search_box")
        self.verticalLayout_5.addWidget(self.search_box)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(ChooseItemUi)
        self.cancel_btn.clicked.connect(ChooseItemUi.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ChooseItemUi)

    def retranslateUi(self, ChooseItemUi):
        _translate = QtCore.QCoreApplication.translate
        ChooseItemUi.setWindowTitle(_translate("ChooseItemUi", "Form"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("ChooseItemUi", "الإسم"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("ChooseItemUi", "المرجع"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("ChooseItemUi", "البيع بـ"))
        self.cancel_btn.setShortcut(_translate("ChooseItemUi", "Esc"))
        self.search_box.setPlaceholderText(_translate("ChooseItemUi", "أكتب هنا للبحث"))
