# Form implementation generated from reading ui file 'error_msg.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(469, 373)
        Dialog.setStyleSheet("background-color:#033a63;")
        self.error_btn = QtWidgets.QPushButton(parent=Dialog)
        self.error_btn.setGeometry(QtCore.QRect(120, 20, 221, 201))
        self.error_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icons/error.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.error_btn.setIcon(icon)
        self.error_btn.setIconSize(QtCore.QSize(200, 200))
        self.error_btn.setFlat(True)
        self.error_btn.setObjectName("error_btn")
        self.err_msg = QtWidgets.QLabel(parent=Dialog)
        self.err_msg.setGeometry(QtCore.QRect(20, 245, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.err_msg.setFont(font)
        self.err_msg.setStyleSheet("color:yellow")
        self.err_msg.setText("")
        self.err_msg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.err_msg.setObjectName("err_msg")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
